// Banco de perguntas — controle de qualidade, nível ensino médio.
// "answer" é o índice da opção correta. Adicione quantas quiser seguindo o mesmo formato.

module.exports = [
  { q: "O que significa a sigla PDCA?", options: ["Planejar, Fazer, Checar, Agir", "Produzir, Dividir, Contar, Avaliar", "Pesquisar, Desenhar, Construir, Aprovar", "Pedir, Decidir, Comprar, Armazenar"], answer: 0 },
  { q: "Qual ferramenta é conhecida como 'espinha de peixe'?", options: ["Gráfico de Pareto", "Diagrama de Ishikawa", "Histograma", "Fluxograma"], answer: 1 },
  { q: "Quantos 'S' tem o programa 5S?", options: ["Três", "Quatro", "Cinco", "Seis"], answer: 2 },
  { q: "O primeiro S do 5S (Seiri) significa:", options: ["Senso de utilização", "Senso de limpeza", "Senso de disciplina", "Senso de saúde"], answer: 0 },
  { q: "Um produto que não atende às especificações é chamado de:", options: ["Conforme", "Não conformidade", "Amostra", "Protótipo"], answer: 1 },
  { q: "A norma internacional mais famosa de gestão da qualidade é a:", options: ["ISO 14001", "ISO 9001", "ISO 45001", "ISO 27001"], answer: 1 },
  { q: "A técnica dos '5 Porquês' serve para:", options: ["Contar peças", "Encontrar a causa raiz de um problema", "Medir temperatura", "Calcular o lucro"], answer: 1 },
  { q: "O princípio de Pareto também é conhecido como regra:", options: ["50/50", "80/20", "10/90", "70/30"], answer: 1 },
  { q: "Kaizen é uma palavra japonesa que significa:", options: ["Melhoria contínua", "Produção rápida", "Estoque zero", "Parada total"], answer: 0 },
  { q: "Verificar uma peça durante a produção para ver se está correta é fazer uma:", options: ["Venda", "Inspeção", "Entrega", "Propaganda"], answer: 1 },
  { q: "Qual gráfico é usado para mostrar quais problemas acontecem com mais frequência?", options: ["Gráfico de Pareto", "Mapa mental", "Cronograma", "Organograma"], answer: 0 },
  { q: "Em qualidade, 'retrabalho' significa:", options: ["Trabalhar em dois turnos", "Corrigir um produto que saiu com defeito", "Contratar mais gente", "Trabalhar de casa"], answer: 1 },
  { q: "A diferença permitida entre a medida ideal e a medida real de uma peça chama-se:", options: ["Tolerância", "Lucro", "Estoque", "Meta"], answer: 0 },
  { q: "Uma lista com itens para marcar durante uma verificação é um:", options: ["Checklist", "Currículo", "Contrato", "Recibo"], answer: 0 },
  { q: "Escolher apenas algumas peças de um lote para testar chama-se:", options: ["Amostragem", "Descarte", "Montagem", "Embalagem"], answer: 0 },
  { q: "Quem é o foco principal de um sistema de gestão da qualidade?", options: ["O gerente", "O cliente", "O fornecedor", "O contador"], answer: 1 },
  { q: "Fazer todos executarem uma tarefa sempre do mesmo jeito é:", options: ["Padronização", "Improvisação", "Terceirização", "Automação"], answer: 0 },
  { q: "O que é uma auditoria de qualidade?", options: ["Uma festa da empresa", "Uma verificação para ver se as regras estão sendo seguidas", "Um treinamento de vendas", "Uma reunião de aniversário"], answer: 1 },
  { q: "O Seiso, um dos 5S, está ligado ao senso de:", options: ["Limpeza", "Ordenação", "Autodisciplina", "Utilização"], answer: 0 },
  { q: "Um 'defeito' em um produto é:", options: ["Uma característica que o cliente adora", "Qualquer falha que faz o produto não funcionar como deveria", "O preço do produto", "A cor da embalagem"], answer: 1 },
  { q: "A fase 'Checar' do PDCA serve para:", options: ["Comprar materiais", "Verificar se o resultado foi o esperado", "Demitir funcionários", "Pintar o produto"], answer: 1 },
  { q: "Registrar quantas vezes um problema acontece em uma tabela simples é usar uma:", options: ["Folha de verificação", "Nota fiscal", "Agenda", "Carteira"], answer: 0 },
  { q: "Qual destas NÃO é uma ferramenta da qualidade?", options: ["Histograma", "Diagrama de Ishikawa", "Fluxograma", "Calculadora científica"], answer: 3 },
  { q: "Prevenir um problema antes que ele aconteça é melhor do que corrigir depois. Isso é chamado de:", options: ["Ação preventiva", "Ação de marketing", "Ação trabalhista", "Ação de estoque"], answer: 0 },
  { q: "O Seiton (5S) é o senso de:", options: ["Ordenação — cada coisa no seu lugar", "Limpeza — nada de sujeira", "Saúde — ambiente seguro", "Disciplina — manter os hábitos"], answer: 0 },
  { q: "Quando um cliente reclama de um produto, a empresa deve:", options: ["Ignorar", "Registrar, investigar a causa e corrigir", "Culpar o cliente", "Aumentar o preço"], answer: 1 },
  { q: "Um fluxograma serve para:", options: ["Desenhar as etapas de um processo", "Medir o peso de uma peça", "Calcular impostos", "Guardar ferramentas"], answer: 0 },
  { q: "Qualidade, de forma simples, é:", options: ["O produto mais caro", "Atender ao que o cliente precisa e espera", "O produto mais bonito", "O produto mais pesado"], answer: 1 },
  { q: "'Fazer certo da primeira vez' evita principalmente:", options: ["Desperdício e retrabalho", "Lucro", "Clientes", "Férias"], answer: 0 },
  { q: "O Shitsuke, último dos 5S, é o senso de:", options: ["Autodisciplina", "Utilização", "Limpeza", "Ordenação"], answer: 0 },
];
